 export const ErrorCodes = Object.freeze({

    // 유효성 검사 관련
    VALIDATION_FAILED: 'VALIDATION_FAILED',      

    // 리소스 관련
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    STORE_NOT_FOUND: 'STORE_NOT_FOUND',
    REVIEW_NOT_FOUND: 'REVIEW_NOT_FOUND',
    CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
    REGION_NOT_FOUND: 'REGION_NOT_FOUND',
    USER_MISSION_NOT_FOUND: 'USER_MISSION_NOT_FOUND',
    MISSION_NOT_FOUND: 'MISSION_NOT_FOUND',

    // 중복 관련
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',    
    STORE_ALREADY_EXISTS: 'STORE_ALREADY_EXISTS',
    REVIEW_ALREADY_EXISTS: 'REVIEW_ALREADY_EXISTS',
    CATEGORY_ALREADY_EXISTS: 'CATEGORY_ALREADY_EXISTS',
    REGION_ALREADY_EXISTS: 'REGION_ALREADY_EXISTS',
    USER_MISSION_ALREADY_EXISTS: 'USER_MISSION_ALREADY_EXISTS',
    USER_MISSION_ALREADY_COMPLETED: 'USER_MISSION_ALREADY_COMPLETED',
    MISSION_ALREADY_EXISTS: 'MISSION_ALREADY_EXISTS',

    // 리소스 생성 실패
    USER_CREATE_FAILED: 'USER_CREATE_FAILED',
    STORE_CREATE_FAILED: 'STORE_CREATE_FAILED',
    REVIEW_CREATE_FAILED: 'REVIEW_CREATE_FAILED',
    CATEGORY_CREATE_FAILED: 'CATEGORY_CREATE_FAILED',
    REGION_CREATE_FAILED: 'REGION_CREATE_FAILED',
    USER_MISSION_CREATE_FAILED: 'USER_MISSION_CREATE_FAILED',
    MISSION_CREATE_FAILED: 'MISSION_CREATE_FAILED',


    // 인증 및 권한 관련
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',

    // 데이터베이스 관련
    DB_OPERATION_FAILED: 'DB_OPERATION_FAILED',

    // 범용
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR', 
    UNKNOWN_ERROR: 'UNKNOWN_ERROR'

});